config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  resources :contacts, only: [:new, :create]
  get '/contact', to: 'static_pages#contact'
  get '/', to: 'static_pages#home'
  root 'static_pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      validate: true
  attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "josh@thebrileys.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/project.rb
class Project < ApplicationRecord
  # t.string "title"
  # t.text "short_description"
  # t.text "long_description"
  # t.string "thumbnail_one"
  # t.string "thumbnail_two"
  # t.string "thumbnail_three"
  # t.string "image"
  # t.string "project_url"
  # t.string "role_in_project"
  # t.string "project_tech_stack"
  # t.datetime "created_at", precision: 6, null: false
  # t.datetime "updated_at", precision: 6, null: false
  # t.string "slug"
  # t.index ["slug"], name: "index_projects_on_slug", unique: true
 
  extend FriendlyId
  friendly_id :title, use: :slugged


  validates :title, presence: true
  validates :long_description, presence: true
  validates :short_description, presence: true
  validates :thumbnail_one, presence: true
  validates :image, presence: true
  validates :project_url, presence: true
  validates :role_in_project, presence: true
  validates :project_tech_stack, presence: true
  has_rich_text :short_description
  has_rich_text :long_description


  def self.get_previous_project(current_project)
    Project.where("projects.id < ? ", current_project.id).order('created_at asc').last
  end
  def self.get_next_project(current_project)
    Project.where("projects.id > ? ", current_project.id).order('created_at asc').first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]
  skip_before_action :verify_authenticity_token
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:success] = 'Message sent!'
    else
      flash.now[:error] = 'Could not send message'
      render :new
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :short_description, :long_description, :thumbnail_one, :thumbnail_two, :thumbnail_three, :image, :project_url, :role_in_project, :project_tech_stack)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :contact]
  def home
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/contacts/create.html.erb
<% provide(:title, 'Email sent') %>
<% provide(:description, 'Let\'s chat about your next web project.') %>
<div class="w-full max-w-3xl p-4 mx-auto">
  <p class="mb-6 tracking-widest uppercase text-jb-cyan">Message Sent</p>
  <h1 class="mb-6 text-h1">Thank you for your message!</h1>
  <p class="mb-6">Thanks for taking the time to reach out to me. I will do my best to respond in a timely manner. If you would like to touch base sooner, please email me at <a href="mailto:devops@thebrileys.com" class="underline hover:no-underline hover:text-jb-cyan">devops@thebrileys.com</a></p>
  <a href="/projects" class="btn btn-primary">Portfolio</a>
</div>

app/views/contacts/new.html.erb
<% provide(:title, 'Contact') %>
<% provide(:description, 'Let\'s chat about your next web project.') %>

<div class="w-full px-4 py-4 mx-auto space-y-12 max-w-7xl lg:px-0">
  <div class="grid gap-8 py-12 border-t lg:gap-12 lg:grid-cols-2">
    <h1 class="text-h2">Get in Touch</h1>
    <div>
      <p class="text-body-1">I’d love to hear about what you’re working on and how I could help. I’m currently looking for new opportunities as a front end developer in a remote position for a Hartford, Boston, or New York based company. But I’m also happy to hear about opportunites that don’t fit that description. I’m a hard-working and positive person who will always approach each task with a sense of purpose and attention to detail. Please do feel free to check out my online profiles below and get in touch using the form.</p>
    </div>
  </div>
  <div class="grid gap-8 py-12 border-t lg:gap-12 lg:grid-cols-2"  x-data="getData()">
    <h2 class="text-h2">Contact Me</h2>
    <div>  
      <div x-show.transition="status || isError">
        <p class="font-bold" x-text="modalHeaderText"></p>
        <p x-text="modalBodyText">></p>
      </div>
      <form x-show="!formSubmitted" class="new_contact" novalidate="true" id="new_contact" accept-charset="UTF-8" @submit.prevent="submitData">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
        <input type="hidden" name="authenticity_token" value="UN0meLToTFWSZSu4D54lEV3uW0MJlwW2F2HyrYRsHlQP0/1inY2E6dTT5coWpQbFrM9NvLI7EalqNKNbuMDsLQ==">
        <div class="space-y-8">
          <div>
            <div class="flex justify-between">
              <label class="block mb-2 text-sm font-bold" for="contact_name">Name</label>
              <small class="opacity-50">Required</small>
            </div>
            <div class="relative">
              <input required="required" class="w-full h-16 p-4 pr-10 bg-jb-gray-dk-blue bg-opacity-5" placeholder="Jane Doe" x-model="contact.name" type="text" name="contact[name]" id="contact_name">
              <div x-show="contact.name.length > 0" class="absolute flex items-center justify-center w-6 h-6 text-sm text-white transform -translate-y-1/2 rounded-full top-1/2 right-4" x-show="contact.email.length > 0" 
                :class="validation.name(contact.name) ? 
                  'bg-green-500' : 'bg-red-500'" >
                <svg x-show="validation.name(contact.name)" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path></svg>
                <svg x-show="!validation.name(contact.name)" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd"></path></svg>
              </div>
            </div>
          </div>

          <div>
            <div class="flex justify-between">
              <label class="block mb-2 text-sm font-bold" for="contact_email">Email</label>
              <small class="opacity-50">Required</small>
            </div>
            <div class="relative">
              <input required="required" class="w-full h-16 p-4 pr-10 bg-jb-gray-dk-blue bg-opacity-5" placeholder="email@example.com" x-model="contact.email" type="text" name="contact[email]" id="contact_email">
              <div class="absolute flex items-center justify-center w-6 h-6 text-sm text-white transform -translate-y-1/2 rounded-full top-1/2 right-4" x-show="contact.email.length > 0" :class="validation.email(contact.email) ? 
                  'bg-green-500' : 'bg-red-500'" >
                <svg x-show="validation.email(contact.email)" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path></svg>
                <svg x-show="!validation.email(contact.email)" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd"></path></svg>
              </div>
            </div>
            
          </div>

          <div>
            <div class="flex justify-between">
              <label class="block mb-2 text-sm font-bold" for="contact_message">Message</label>
              <small class="opacity-50">Required</small>
            </div>
            <div class="relative">
              <textarea rows="8" cols="40" required="required" class="w-full p-4 h-86 bg-jb-gray-dk-blue bg-opacity-5" x-model="contact.message" placeholder="How can I help?" name="contact[message]" id="contact_message"></textarea>
              <div class="absolute flex items-center justify-center w-6 h-6 text-sm text-white transform -translate-y-1/2 rounded-full top-1/2 right-4" x-show="contact.message.length > 0" :class="validation.message(contact.message) ? 
                'bg-green-500' : 'bg-red-500'" >
                <svg x-show="validation.message(contact.message)" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path></svg>
                <svg x-show="!validation.message(contact.message)" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd"></path></svg>
              </div>
            </div>
          </div>

          <div class="hidden">
            <input hint="Leave this field blank!" class="hidden" type="text" name="contact[nickname]" id="contact_nickname">
          </div>
          <p>Form is valid: <span x-text="validation.formValidity"></span></p>
          <button class="btn btn-secondary" x-text="buttonLabel"></button>
        </div>
      </form>


    </div>
  </div>

</div>

<script>
  function getData() {
    return {
      contact: {
        name: "",
        email: "",
        message: "",
      },
      status: false,
      loading: false,
      isError: false,
      formSubmitted: false,
      modalHeaderText: "",
      modalBodyText: "",
      buttonLabel: 'Send Message',
      validation: {
        name(name) {
          return name.length > 1;
        },
        email(email) {
          var re = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
          return re.test(email);
        },
        message(message) {
          return message.length > 10;
        },
        formValidity() {
          return this.validation.name(this.contact.name) && this.validation.email(this.contact.email) && this.validation.message(this.contact.message);
        }
      },
      submitData() {
        if (!this.contact.email.length ||
          !this.contact.name.length ||
          !this.contact.message.length) {
          alert("Please fill out all required field and try again!")
          return;
        }
        this.buttonLabel = 'Submitting...'
        this.loading = true;
        fetch('<%= contacts_path %>', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify(this.contact)
          })
          .then((response) => {
            if (response.status === 201 || response.status === 200) {
              this.modalHeaderText = "Thank you!"
              this.modalBodyText = "Thanks for taking the time to reach out to me. I will do my best to respond in a timely manner. If you would like to touch base sooner, please email me at devops@thebrileys.com.";
              this.status = true;
            } else {
              throw new Error("Your registration failed");
            }
          })
          .catch((error) => {
            this.modalHeaderText = "Ooops Error!"
            this.modalBodyText = error.message;
            this.isError = true;
          })
          .finally(() => {
            this.loading = false;
            this.contact.email = ''
            this.contact.name = '' 
            this.contact.message = '' 
            this.buttonLabel = 'Submit'
            this.formSubmitted = true;
          })
        }
      }
    }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head lang="en">
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="description" content="<%= yield(:description) %>">
    <meta property="og:title" content="<%= yield(:title) %>">
    <meta property="og:site_name" content="Briley Creative">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://enigmatic-scrubland-23648.herokuapp.com/">
    <meta property="og:image" content="https://res.cloudinary.com/dwjulenau/image/upload/v1634989625/josh-portfolio/briley-creative-og-image.jpg">
    <meta property="og:image:width" content="627">
    <meta property="og:image:height" content="1200">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@joshuabriley">
    <meta name="twitter:url" content="https://enigmatic-scrubland-23648.herokuapp.com/">
    <meta name="twitter:title" content="<%= yield(:title) %>">
    <meta name="twitter:description" content="<%= yield(:description) %>">
    <meta name="twitter:image" content="https://res.cloudinary.com/dwjulenau/image/upload/v1634989625/josh-portfolio/briley-creative-og-image.jpg">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ibarra+Real+Nova:wght@400;700&family=Public+Sans:wght@400;700&display=swap" rel="stylesheet">
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//unpkg.com/alpinejs" defer></script>
  </head>
  <body class="flex flex-col min-h-screen">
    <%= render '/shared/header' %>
    <main class="flex-grow">
      <%= yield %>
    </main>
    <%= render '/shared/footer' %>
  </body>
</html>

app/views/projects/edit.html.erb
<% provide(:title, "Edit #{@project.title}") %>
<% provide(:description, 'Edit details about this project') %>

<div class="w-full px-4 py-4 pb-24 mx-auto space-y-12 max-w-screen-2xl lg:px-0">
  <h1 class="text-h2">Editing <span class="text-jb-cyan"><%= @project.title %></span> Project</h1>
  <%= render 'form', project: @project %>
</div>

app/views/projects/index.html.erb
<% provide(:title, "Portfolio") %>
<% provide(:description, 'Briley Creative Web design and development portfolio') %>

<div class="w-full px-4 py-4 pb-24 mx-auto space-y-24 max-w-7xl lg:px-0 lg:space-y-32">
  <% @projects.each.with_index do |project, i| %>
    <div class="grid gap-8 md:grid-cols-2 md:pb-0">
      <div class="flex items-center <% if i.even? %>md:order-0<%else%>md:order-1<%end%>">
        <img src="<%= project.thumbnail_one %>" alt="">
      </div>
      <div class="md:px-12 <% if i.even? %>md:order-1<%else%>md:order-0<%end%>">
        <div class="flex items-center h-full py-6 border-t border-b">
            <div>
              <h2 class="mb-4 text-h2">
                <%= project.title %>
              </h2>
              <div class="mb-4 text-body-1">
                <%= project.short_description %>
              </div>
              <div class="mb-4">
                <%= link_to 'View Project', project , class: 'btn btn-primary' %>
                <% if current_user && current_user.admin %>
                <%= link_to 'Edit', edit_project_path(project), class: 'btn btn-primary' %> 
                <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' %>
                <% end %>
              </div>
            </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= render '/shared/pitch' %>
  <% if current_user && current_user.admin %>
  <%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/projects/new.html.erb
<% provide(:title, "New Portfolio Entry") %>
<% provide(:description, 'Briley Creative Web design and development portfolio') %>

<div class="w-full px-4 py-4 mx-auto space-y-12 max-w-7xl lg:px-0">
  <h1 class="text-h1">New Project</h1>

  <%= render 'form', project: @project %>

  <div class="pb-12">
    <%= link_to 'Back', projects_path %>
  </div>
</div>

app/views/projects/show.html.erb
<% provide(:title, "#{@project.title} Project Details") %>
<% provide(:description, 'Briley Creative Web design and development portfolio') %>
<div class="w-full px-4 pb-16 mx-auto space-y-12 max-w-7xl lg:px-0 lg:space-y-32 lg:pb-32">
  <img src="<%= @project.image %>"  alt="" class="w-full">

  <div class="grid gap-10 lg:grid-cols-3 lg:gap-20">
    <div class="py-8 border-t border-b md:border-b-0 md:col-span-1">
      <div class="lg:sticky lg:top-8">
        <div>
        <h1 class="mb-6 text-h1"><%= @project.title %></h1>
        <div class="mb-12 text-body-1 text-jb-gray-dk-blue "><%= @project.short_description %></div>
      </div>
      <div class="mb-6 space-y-4 text-sm font-bold text-jb-cyan" >
        <p><%= @project.role_in_project %></p>
        <p><%= @project.project_tech_stack %></p>
      </div>
      <a href="<%= @project.project_url %>" class="btn btn-primary" target="_blank" rel="noreferrer">Visit Website</a>
      </div>
    </div>

    <div class="md:col-span-2">
       <div class="mb-10">
        <h2 class="mb-8 text-h3">Project Background</h2>
        <div class="text-body-1"><%= @project.long_description %></div>
      </div>
      
      <div class="space-y-10">
        <h3 class="text-h3">Static Preview</h3>
        <div class="space-y-8">
          <img src="<%= @project.thumbnail_one %>" alt="Project thumbnail" class="w-full">
          <img src="<%= @project.thumbnail_two %>" alt="Project thumbnail" class="w-full">
        </div>
      </div>


      <div class="mt-10">
        <% if current_user && current_user.admin %>
        <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-primary' %>
        <%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' %>
        <% end %>
        <%= link_to 'Back', projects_path, class: 'btn btn-primary' %>
        
      </div>
    </div>
  </div>
  <div class="grid grid-cols-2 border-t border-b divide-x">
    <div class="py-6">
      <% unless @project.id == Project.first.id  %>
        <div class="flex items-center space-x-2">
          <%= heroicon "chevron-left", options: { class: "h-8 w-8 opacity-50" } %> 
          <div>
            <p class="font-serif text-2xl lg:text-3xl">            
              <%= link_to Project.get_previous_project(@project).title, Project.get_previous_project(@project)  %>
            </p>
            <span class="text-sm opacity-50">Previous Project</span> 
          </div>
        </div>
      <% end %>
    </div>
    <div class="flex flex-col py-6">
      <% unless  @project.id == Project.last.id   %>
        <div class="flex items-center justify-end space-x-2 text-right">
          <div>
            <p class="font-serif text-2xl lg:text-3xl">  
              <%= link_to  Project.get_next_project(@project).title, Project.get_next_project(@project) %>
            </p>
            <span class="text-sm opacity-50">Next Project</span> 
          </div>  
          <%= heroicon "chevron-right", options: { class: "h-8 w-8 opacity-50" } %>       
        </div>
      <% end %>
    </div>
  </div>
  <%= render '/shared/pitch' %>
</div>

app/views/shared/_header.html.erb
<header class="text-jb-gray-dk-blue">
  <div class="flex items-center justify-between w-full px-4 mx-auto h-28 max-w-7xl">
    <% if controller.action_name == 'home' %>
      <%= render '/shared/logo' %>
    <% else %>
      <a href="/" aria-label="Home page">
        <%= render '/shared/logo' %>
      </a>
    <% end %>
    <nav x-data="{menuIsVisible: false}" aria-label="Main Site Nav" class="relative flex items-center h-full" @click.outside="menuIsVisible = false">
      <button @click="menuIsVisible = !menuIsVisible" aria-label="Main Menu Toggle" class="lg:hidden">
        <span x-show="!menuIsVisible"><%= heroicon "menu", options: { class: "h-8 w-8" } %></span>
        <span x-show="menuIsVisible"><%= heroicon "x", options: { class: "h-8 w-8" } %></span>
      </button>
      <ul 
        
        class="absolute right-0 z-20 p-6 space-y-6 text-sm text-white uppercase duration-200 origin-top-right transform lg:space-y-0 lg:gap-4 transition-trasnform bg-jb-gray-dk-blue lg:text-jb-gray-dk-blue lg:bg-white lg:relative lg:flex lg:items-center lg:h-full lg:top-0 lg:p-0 w-72 lg:w-auto"
        :class="menuIsVisible ? 'translate-y-0 top-20' : 'opcacity-0 lg:opacity-1 -translate-y-full lg:translate-y-0 top-0'"
      >
        <li class="flex items-center h-full"><a href="/" class="flex items-center w-full h-full hover:text-jb-cyan <% if controller.action_name == 'home' %>text-jb-cyan<% end %>">Home</a></li>
        <li class="flex items-center h-full"><a href="/projects" class="flex items-center w-full h-full hover:text-jb-cyan <% if controller_name == 'projects' %>text-jb-cyan<% end %>">Portfolio</a></li>
        <li class="flex items-center h-full"><a href="/contacts/new" class="flex items-center w-full h-full hover:text-jb-cyan <% if controller_name == 'contacts' %>text-jb-cyan<% end %>">Contact</a></li>
      </ul>
    </nav>
    
  </div>
</header>

app/views/shared/_pitch.html.erb
<div class="items-center space-y-10 md:flex md:space-y-0 md:space-x-12">
  <h3 class="text-center text-h2">Interested in doing <span class="md:block">a project together?</span></h3>
  <div aria-hidden="true" class="hidden h-px md:flex md:flex-grow bg-jb-form-gray"></div>
  <div class="flex justify-center">
    <a href="/contacts/new" class="btn btn-primary">Contact Me</a>
  </div>
</div>